baseURL: https://ajiekusumadhany.com/
languageCode: en-us
defaultContentLanguage: en-us
title: "Ajie Ikrus Kusumadhany"
enableRobotsTXT: true
enableEmoji: true
theme: hugo-theme-luna
timeout: 60000
timeZone: Asia/Jakarta

# use git commit log to generate lastmod record
enableGitInfo: false

# enable CJK language support
hasCJKLanguage: false

# 每页显示文章数量
# pagination size
paginate: 10

# 启用谷歌统计
# google analytics tracking code
# googleAnalytics: UA-98634098-1

# 版权信息，默认为 author.name ↓
# default: author.name ↓
# copyright: ""

permalinks:
  # 文章链接的格式
  # Format of posts links
  posts: # 2019/01/01/hello-world.html
  pages: /:slug # about.html

author:
  name: Ajie Kusumadhany

frontmatter:
  lastmod:
    - :git
    - lastmod
    - :fileModTime
    - date
    - publishDate
    - :default

taxonomies:
  tag: "tags"
  category: "categories"

summaryLength: 70
canonifyURLs: false
relativeURLs: false

# see https://gohugo.io/content-management/image-processing/#imaging-configuration
imaging:
  resampleFilter: CatmullRom
  quality: 95
  anchor: smart

caches:
  getresource:
    dir: :resourceDir/_gen
    maxAge: 24h

# See https://gohugo.io/about/hugo-and-gdpr/
privacy:
  googleAnalytics:
    anonymizeIP: true
  youtube:
    privacyEnhanced: true

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml

# all supported pages
$manuMain:
  - &mainMenuHome
    name: Home
    weight: 10
    identifier: home
    params:
      icon: eva eva-home
    url: /
  - &mainMenuAbout
    name: About
    weight: 20
    identifier: about
    params:
      icon: eva eva-person
    url: /about/
  - &mainMenuLinks
    name: Links
    weight: 30
    identifier: links
    params:
      icon: eva eva-link-2
    url: /links/
  - &mainMenuArchives
    name: Archives
    weight: 40
    identifier: archives
    params:
      icon: eva eva-archive
    url: /archives/
  - &mainMenuTags
    name: Tag
    weight: 50
    identifier: tags
    params:
      icon: eva eva-pricetags
    url: /tag/
  - &mainMenuCategories
    name: Category
    weight: 60
    identifier: categories
    params:
      icon: eva eva-folder
    url: /category/
  - &mainMenuTwitter
    name: Twitter
    weight: 70
    identifier: twitter
    params:
      icon: eva eva-twitter
    url: /twitter/
  - &mainMenuGitHub
    name: GitHub
    weight: 80
    identifier: github
    params:
      icon: eva eva-github
    url: /github/
  - &mainMenuSearch
    name: Search
    weight: 999
    identifier: search
    params:
      icon: eva eva-search
    url: /search/

# If you don't want the navbar, you can delete this paragraph
menu:
  main:
    - *mainMenuHome
    - *mainMenuAbout
    - *mainMenuLinks
    - *mainMenuArchives
    - *mainMenuGitHub
    - *mainMenuSearch

  # sub:
  #   - name: Categories
  #     weight: 20
  #     identifier: categories
  #     params:
  #       icon: eva eva-folder
  #     url: /categories/
  #   - name: Tags
  #     weight: 30
  #     identifier: tags
  #     params:
  #       icon: eva eva-pricetags
  #     url: /tags/

markup:
  highlight:
    style: dracula
    guessSyntax: true
    tabWidth: 4
    lineNumbersInTable: true
    lineNos: true
    codeFences: true
  goldmark:
    renderer:
      unsafe: true # enable html in markdown

# .Site.Params
params:
  # CDN URL
  publicCDN: ""
  # Display title and description at the top of the page, use .Site.Title and .Site.Params.Description
  topTitle: false

  # Create a Announcement section at the top of the home page
  announcement:
    enabled: true
    file: "readme.md" # assets/README.md

  # Comment system
  comments:
    enabled: true
    provider: "disqus" # custom | giscus
    giscus: &giscus
      repo: "ajiekusumadhany/blog"
      repoID: "R_kgDOKK9yhA"
      category: "Comments"
      categoryID: "DIC_kwDOKK9yhM4CY1RN"
      mapping: "title"
      reactionsEnabled: 1
      emitMetadata: 0
      lazy: true
      lang: "id"

  # RSS configuration
  rss:
    # If false, you must set Output Formats, see: https://gohugo.io/templates/output-formats#customizing-output-formats
    enabled: true
    # Output full text
    fullText: true

  # If false, you must set Output Formats, see: https://gohugo.io/templates/output-formats#customizing-output-formats
  sitemap: true

  # Site theme colors
  # themeColor: "#facd60"
  themeColor: "#0D9488"

  # Set website to black and white, usually for mourning events
  blackAndWhite: false

  # Output a nice console log
  console:
    enabled: true
    leftColor: "#0D9488"
    leftText: "Ajie Kusumadhany"
    rightColor: "#0D9488"
    rightText: " ❤ World"

  # Title counter
  headlineCounter: false

  # Fixed navigation bar
  fixedNav: true


  # font: 'Roboto, "Helvetica Neue", Helvetica, Arial, sans-serif'
  font: "Lato,'Roboto Condensed','Noto Sans TC','PingFang TC','Helvetica Neue','SF Pro TC',Helvetica,arial,'Microsoft JhengHei','Microsoft YaHei',Arial,sans-serif"

  # ts/custom.ts
  customScript:
    enabled: false
    pjax: true # Auto-reload in pjax mode

  # Show site runtime
  runTime:
    enabled: true
    # 网站创建时间
    # Site creation time
    creatTime: 2023/02/04

  # Site creation year
  since: "2023"

  # show warning when outdated info detected
  outdatedInfoWarning:
    enabled: true
    # A timeout reminder will be displayed if the last modification time exceeds that number of days
    day: 90

  # Automatic switching of night mode (using device settings)
  autoDarkMode: true

  share:
    twitter: true
    facebook: true
    weibo: false
    copyLinkText: true
    qrcode: true

  qrcodeAPI: "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data="

  # license
  license:
    enabled: false
    name: "CC BY-NC-ND 4.0"
    icon: "Cc-by-nc-nd.svg" # in assets folder
    url: "https://creativecommons.org/licenses/by-nc-nd/4.0"

  # Display i18n toggle button
  i18nlist: false

  # GitHub 
  # github page
  github:
    id: "ajiekusumadhany" # github user id
    minStars: 0 # / min stars

  # tweet page
  twitter:
    enabled: true
    rsshub: "https://rsshub.rssforever.com" # rsshub url, see https://github.com/DIYgod/RSSHub
    id: "ajiekusumadhany" # Twitter ID
    # If enabled, Hugo will download videos and images from the Tweet and optimize them
    imageProcessing: true


  # lazyload image
  lazyload: true

  bionicReading:
    enabled: true
    autoBionic: false
    skipLinks: false
    excludeWords: []
    excludeNodeNames: [] 
    excludeClasses: ["github"]

  # enable google translate in footer
  googleTranslate: true

  # Optimize Chinese typography, see: https://github.com/vinta/pangu.js
  pangu: true

  # enable local search plugin
  search: true

  # For outdated reminders
  lastmod: true

  # show reading time
  readingTime: true

  # show word count
  wordCount: false

  # Show table of contents, You can enable it separately in the page
  toc:
    enabled: true
    # When the article word count is greater than this value, the TOC will be displayed
    wordCount: 400

  # encryption articles
  HugoEncrypt:
    # default password
    Password: "ajie357"
    # "session" or "local"
    # or "local"
    Storage: "session"

  # Enable pjax with swup.js
  pjax: true

  # use service worker
  pwa: true

  # katex
  katex: true

  # backtop button
  backtop: true

  # 文章封面图片纵横比
  # article image aspect ratio
  featuredImageHeight: "42%" #42% | false

  # Default post card featured image, not displayed on content pages
  defaultFeaturedImage: https://source.unsplash.com/random/1600x900/?anime

  # Optimize your images and SEO
  imageProcessing:
    cover: true
    content: true
    autoResize:
      - 1080
      - 1440
    webp: true

  opengraph:
    twitter: # see https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started
      cardType: summary_large_image # summary | summary_large_image
      site: "@ajiekusumadhany"
    image: "featured.png" # in assets folder | false

  author: Ajie Kusumadhany
  keywords:
    - Ajie Kusumadhany
    - Ajie Ikrus Kusumadhany
  description: "Media online, tempat saya mencatat segala hal yang ingin saya catat dan berbagi informasi melalui tulisan di internet."

build:
  noJSConfigInAssets: true

languages:
  en-us:
    contentDir: content
    languageName: Indonesia
    params:
      languageIcon: "images/i18n/en-us.svg" # in assets folder

    menu:
      main:
        - *mainMenuHome
        - *mainMenuArchives
        - *mainMenuSearch
        - *mainMenuLinks
        - *mainMenuTwitter
staticDir:
  - static